---
.gitlab-ci.yml:
  delete: true
.travis.yml:
  dist: 'bionic'
appveyor.yml:
  delete: true
Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        version: '~> 1.15.0'
      - gem: 'rspec-puppet-utils'
        version: '~> 3.4'
Rakefile:
  changelog_version_tag_pattern: '%s'
  requires:
    - 'puppet-strings/tasks'
spec/spec_helper.rb:
  mock_with: ':rspec'
  coverage_report: true
  default_facter_version: '3.14.0'

